---
- name: Change owner of {{ data_dir }}
  file:
    path: {{ data_dir }}
    owner: elastic
    group: elastic
    mode: 0700
    state: directory

- name: Change owner and permissions of {{ data_dir }}/elastic
  file:
    path: "{{ data_dir }}/elastic"
    state: directory
    owner: elastic
    group: elastic
    mode: 0700

- name: Change owner and permissions of {{ data_dir }}/docker
  file:
    path: "{{ data_dir }}/docker"
    state: directory
    owner: elastic
    group: elastic
    mode: 0700
