---
- name: Make sure {{ data_dir }} exists
  file:
    path: "{{ data_dir }}"
    state: directory

- name: Create the volume
  lvg:
    vg: lxc
    pvs: /dev/{{ device_name }}
    force: true

- name: Define size of swap
  shell: SWAP_MAX_SIZE=$(sudo vgdisplay --units M lxc | grep "VG Size" | awk '{ print mem=int(0.07*$3) }'); grep MemTotal /proc/meminfo | awk -v MAXMEM=${SWAP_MAX_SIZE} '{ mem=int($2/(2*1024)); if(mem>MAXMEM) mem=MAXMEM; print mem; }'
  register: swap_size

- name: Create swap volume
  lvol:
    vg: lxc
    lv: swap
    size: "{{swap_size.stdout}}m"
    force: true

- name: Create data volume
  lvol:
    vg: lxc
    lv: data
    size: 100%FREE
    force: true

- name: Setup swap
  command: mkswap /dev/lxc/swap

- name: Create xfs filesystem on /dev/lxc/data
  filesystem:
    fstype: xfs
    dev: /dev/lxc/data

- name: Mount /dev/lxc/data
  mount:
    path: "{{ data_dir }}"
    state: mounted
    src: /dev/lxc/data
    fstype: xfs
    opts: "defaults,pquota,prjquota,x-systemd.automount"

- name: Mount /dev/lxc/swap
  mount:
    src: "/dev/lxc/swap"
    name: "swap"
    fstype: "swap"
    opts: "swap"
    dump: "0"
    passno: "0"
    state: "present"

- name: Enable all swap devices
  command: swapon -a
  args:
    warn: no
