---
- name: sysctl_scripts.yml || load ip_conntrack if needed
  modprobe:
    name: ip_conntrack
    state: present

- name: Create sysctl settings file
  file:
    path: "{{ sysctl_settings_file }}"
    state: touch

- name: sysctl_scripts.yml || set sysctl items
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
    state: present
    sysctl_set: yes 
    sysctl_file: "{{ sysctl_settings_file }}"
  with_items:
  -  { name: 'net.ipv4.tcp_max_syn_backlog', value: '65536' }
  -  { name: 'net.core.somaxconn', value: '32768' }
  -  { name: 'net.core.netdev_max_backlog', value: '32768' }
  -  { name: 'vm.max_map_count', value: '262144' }
  -  { name: 'vm.swappiness', value: '1' }
  -  { name: 'net.ipv4.tcp_keepalive_time', value: '1800' }
  -  { name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '7200' }
  -  { name: 'net.netfilter.nf_conntrack_max', value: '262140' }
